### ISSUE TITLE
Q: when extending model, also generate claims

### ISSUE THREAD

**Issue by danielwertheim** [IdentityServer/IdentityServer3.MembershipReboot#33]
If you extend your model as in sample: https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/MembershipReboot/WebHost/MR/CustomUser.cs#L32

And want e.g. `FirstName` to control if a `given_name claim` should be added/removed for the account, what is the preferred way of doing that? Was looking into overriding `UserAccountService.Update(CustomUser account)` and placing calls to `AddClaim` vs `RemoveClaim` but that recursively calls it self, so what is the preferred way?

**Comment by brockallen** [comment]
I don't follow.

**Comment by danielwertheim** [comment]
Are you saying that the value `Foo` assigned to `FirstName` will be stored as a claim with key `given_name` and value `Foo`?

**Comment by brockallen** [comment]
Sorry -- lost track of this issue/question.

Claims are stored in the claims child table. Custom properties are stored as columns. The problem is that custom properties don't automatically get mapped as claims, so you need to do that somewhere. When integrating with IdSvr, then you coul[d do that in the GetProfileData API on the user service.

Sorry for the delay. HTH

**Comment by brockallen** [comment]
All set on this?

**Comment by danielwertheim** [comment]
Yes, thanks. Ended up in writing own user service using custom membership domain.
